main:
  #- name: "About"
  #  url: "about"
  #  enable: false
  #  weight: 1
  - name: "Blog"
    url: "https://build.prestashop.com"
    weight: 1
  - name: "GitHub"
    url: "https://github.com/PrestaShop/PrestaShop/"
    weight: 2
  - name: "Contribute"
    url: "https://devdocs.prestashop.com/1.7/contribute/"
    weight: 3
  - name: "Resources"
    weight: 4

footer_left:
  - name: Blog
    url: "https://build.prestashop.com"
  - name: GitHub
    url: "https://github.com/PrestaShop/PrestaShop/"
  - name: Slack
    pageRef: "slack"

footer_middle:
  - name: "User documentation"
    url: "https://prestashop.gitbook.io/english-documentation-1-7/"
    weight: 1
  - name: "Developer documentation"
    url: "https://devdocs.prestashop.com"
    weight: 2
  - name: "Specifications"
    url: "https://build.prestashop.com/prestashop-specs/"
    weight: 3

footer_right:
  - name: "Code of conduct"
    pageRef: "code-of-conduct"
  - name: "Maintainer's guide"
    pageRef: "maintainers-guide"
